apiVersion: apps/v1
kind: Deployment
metadata:
  name: microprofile-deploy
  labels:
    apps: microprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: microprofile-pod
  template:
    metadata:
      labels:
        apps: microprofile-pod
    spec:
      containers:
      - name: teacherseverywhere
        image: teacherseverywhere:0.0.8
        ports:
        - containerPort: 9080
          name: http
        - containerPort: 9443
          name: https