apiVersion: v1
kind: Service
metadata:
  name: microprofile-service
spec:
  selector:
    apps: microprofile-pod
 #This should match the label we had for our pods
  ports:
  - protocol: TCP
    port: 9080
  type: NodePort